Repository explosion/spaCy, pull requests merged in 2018-03, with the labels that each got.

#2065 Broken github link to NLTK
  .github/contributors/willismonroe.md
  CONTRIBUTING.md
  website/usage/spacy-101.jade
Labels: docs

#2080 Turkish data
  spacy/lang/tr/examples.py
  spacy/lang/tr/lex_attrs.py
  spacy/lang/tr/stop_words.py
  spacy/lang/tr/tokenizer_exceptions.py
Labels: enhancement, language / turkish

#2012 Fix Spanish noun_chunks failure caused by typo
  .github/contributors/alldefector.md
  spacy/lang/es/__init__.py
  spacy/lang/es/syntax_iterators.py
Labels: bug, language / spanish

#2095 Quick typo fix
  spacy/lang/en/lemmatizer/lookup.py
Labels: bug, language / english

#2102 Fix typo ditectory -> directory
  .github/contributors/doug-descombaz.md
  website/usage/_processing-pipelines/_pipelines.jade
Labels: docs

#2108 Improve label management in parser and NER
  requirements.txt
  setup.py
  spacy/about.py
  spacy/cli/conll17_ud_eval.py
  spacy/cli/train.py
  spacy/cli/ud_train.py
  spacy/gold.pyx
  spacy/language.py
  spacy/pipeline.pyx
  spacy/scorer.py
  spacy/syntax/_state.pxd
  spacy/syntax/arc_eager.pyx
  spacy/syntax/ner.pyx
  spacy/syntax/nn_parser.pyx
  spacy/syntax/nonproj.pyx
  spacy/syntax/transition_system.pxd
  spacy/syntax/transition_system.pyx
  spacy/tests/test_textcat.py
  spacy/tokens/doc.pxd
  spacy/util.py
  website/api/goldcorpus.jade
Labels: enhancement

#2116 Minor enhancements
  spacy/lang/en/stop_words.py
  website/usage/_v2/_features.jade
Labels: docs, enhancement

#2123 drop should be a float
  website/api/pipe.jade
Labels: docs

#2127 Docs patch
  website/api/doc.jade
  website/usage/_spacy-101/_similarity.jade
Labels: docs

#2131 Fix typo in documentation for displacy Visualizer
  .github/contributors/calumcalder.md
  website/api/_top-level/_displacy.jade
Labels: docs

#2110 [v1.x] Backport 2.x's avoidance of 'import pip'
  requirements.txt
  spacy/cli/link.py
  spacy/tests/test_cli.py
Labels: third-party, v1

#2137 Add example for visualizing word vectors with TensorBoard Projector
  .github/contributors/justindujardin.md
  examples/vectors_tensorboard.py
Labels: examples

#2140 My contributor agreement
  .github/contributors/ottosulin.md
  spacy/lang/fi/lex_attrs.py
  spacy/lang/fi/stop_words.py
Labels: meta

#2138 Fixed few Finnish stop words
  spacy/lang/fi/stop_words.py
Labels: enhancement, language / finnish

#2142 more exceptions
  spacy/lang/pl/tokenizer_exceptions.py
Labels: enhancement, language / polish

#2158 💫 Fix loading of multiple vector models
  spacy/_ml.py
  spacy/cli/train.py
  spacy/language.py
  spacy/pipeline.pyx
  spacy/syntax/nn_parser.pyx
  spacy/tests/conftest.py
  spacy/tests/regression/test_issue1660.py
  spacy/tests/serialize/test_serialize_language.py
  spacy/vectors.pyx
  spacy/vocab.pyx
Labels: bug, feat / vectors

#2159 💫 Fix token.ent_iob after doc.merge(), and ensure consistency in doc.ents
  spacy/tests/doc/test_add_entities.py
  spacy/tests/doc/test_span_merge.py
  spacy/tokens/doc.pyx
Labels: bug, feat / ner

#2155 Add support for Vietnamese in spaCy by leveraging Pyvi, an external Vietnamese tokenizer
  .github/contributors/trungtv.md
  spacy/lang/vi/__init__.py
  spacy/lang/vi/lex_attrs.py
  spacy/lang/vi/stop_words.py
  spacy/lang/vi/tag_map.py
Labels: enhancement, lang / vi

#2152 💫 Tidy up dependencies
  examples/pipeline/custom_component_countries_api.py
  requirements.txt
  setup.py
  spacy/cli/download.py
  spacy/cli/validate.py
  spacy/compat.py
  spacy/pipeline.pyx
  spacy/util.py
  spacy/vectors.pyx
Labels: install
