Repository explosion/spaCy, pull requests merged in 2018-11, with the labels that each got.

#2909 Removed space in docs + added contributor indo
  .github/contributors/mikelibg.md
  website/usage/_v2/_features.jade
Labels: docs

#2919 Include universe spec for spacy-wordnet component
  .github/contributors/frascuchon.md
  website/universe/universe.json
Labels: docs

#2886 Check if the word is in one of the regular lists specific to each POS for French Language
  spacy/lang/fr/lemmatizer/lemmatizer.py
Labels: bug, enhancement, feat / lemmatizer, lang / fr

#2925 💫 Allow matching non-ORTH attributes in PhraseMatcher
  spacy/matcher.pyx
  spacy/tests/matcher/test_phrase_matcher.py
Labels: enhancement, feat / matcher, 🌙 nightly

#2927 💫 Create random IDs for SVGs to prevent ID clashes
  spacy/displacy/render.py
Labels: bug, feat / visualizers

#2931 💫 Add experimental ULMFit/BERT/Elmo-like pretraining
  spacy/__main__.py
  spacy/cli/__init__.py
  spacy/cli/pretrain.py
  spacy/cli/train.py
Labels: enhancement, training, 🌙 nightly

#2949 fixes symbolic link on py3 and windows
  .github/contributors/cicorias.md
  spacy/compat.py
  spacy/tests/test_symlink_windows.py
Labels: bug, feat / cli

#2965 Update tests for pytest 4.x
  requirements.txt
  spacy/tests/lang/de/test_exceptions.py
  spacy/tests/lang/en/test_sbd.py
  spacy/tests/lang/en/test_text.py
  spacy/tests/lang/hu/test_tokenizer.py
  spacy/tests/regression/test_issue1547.py
  spacy/tests/regression/test_issue1622.py
  spacy/tests/regression/test_issue1945.py
  spacy/tests/regression/test_issue2385.py
  spacy/tests/tokenizer/test_urls.py
Labels: tests, third-party

#2943 💫 Refactor CLI
  .flake8
  spacy/__main__.py
  spacy/cli/__init__.py
  spacy/cli/_messages.py
  spacy/cli/convert.py
  spacy/cli/converters/__init__.py
  spacy/cli/converters/conll_ner2json.py
  spacy/cli/converters/conllu2json.py
  spacy/cli/converters/conllubio2json.py
  spacy/cli/converters/iob2json.py
  spacy/cli/converters/jsonl2json.py
  spacy/cli/debug_data.py
  spacy/cli/download.py
  spacy/cli/evaluate.py
  spacy/cli/info.py
  spacy/cli/init_model.py
  spacy/cli/link.py
  spacy/cli/package.py
  spacy/cli/profile.py
  spacy/cli/schemas/__init__.py
  spacy/cli/train.py
  spacy/cli/ud/__init__.py
  spacy/cli/ud/conll17_ud_eval.py
  spacy/cli/ud/ud_run_test.py
  spacy/cli/ud/ud_train.py
  spacy/cli/validate.py
  spacy/cli/vocab.py
  spacy/displacy/__init__.py
  spacy/util.py
  website/api/_top-level/_util.jade
Labels: enhancement, feat / cli, 🌙 nightly

#2968 💫 Use README.md instead of README.rst
  MANIFEST.in
  README.md
  README.rst
  setup.py
Labels: docs, enhancement, pip, 🌙 nightly

#2966 💫 Use Blis for matrix multiplications
  .appveyor.yml
  bin/cythonize.py
  requirements.txt
  setup.py
  spacy/pipeline.pyx
  spacy/syntax/_parser_model.pyx
  spacy/syntax/nn_parser.pyx
  spacy/util.py
Labels: enhancement, 🌙 nightly, 🔮 thinc

#2972 💫 Update hyper-parameters after NER random search
  spacy/_ml.py
  spacy/cli/train.py
  spacy/pipeline.pyx
  spacy/syntax/nn_parser.pyx
Labels: enhancement, 🌙 nightly

#2977 Fix bug where Vocab.prune_vectors did not use 'batch_size'
  .github/contributors/ALSchwalm.md
  spacy/vocab.pyx
Labels: bug, feat / vectors

#2981 OntoNotes url fix
  website/api/_annotation/_named-entities.jade
Labels: docs

#2988 Fix is_ascii documentation
  .github/contributors/wxv.md
  website/api/token.jade
Labels: docs

#2932 💫 New JSON helpers, training data internals & CLI rewrite
  requirements.txt
  setup.py
  spacy/__main__.py
  spacy/cli/__init__.py
  spacy/cli/_messages.py
  spacy/cli/convert.py
  spacy/cli/converters/__init__.py
  spacy/cli/converters/conll_ner2json.py
  spacy/cli/converters/conllu2json.py
  spacy/cli/converters/conllubio2json.py
  spacy/cli/converters/iob2json.py
  spacy/cli/converters/jsonl2json.py
  spacy/cli/debug_data.py
  spacy/cli/download.py
  spacy/cli/evaluate.py
  spacy/cli/info.py
  spacy/cli/init_model.py
  spacy/cli/link.py
  spacy/cli/package.py
  spacy/cli/pretrain.py
  spacy/cli/profile.py
  spacy/cli/schemas/__init__.py
  spacy/cli/schemas/meta.json
  spacy/cli/schemas/training.json
  spacy/cli/train.py
  spacy/cli/ud/__init__.py
  spacy/cli/ud/conll17_ud_eval.py
  spacy/cli/ud/ud_run_test.py
  spacy/cli/ud/ud_train.py
  spacy/cli/validate.py
  spacy/cli/vocab.py
  spacy/compat.py
  spacy/displacy/__init__.py
  spacy/errors.py
  spacy/gold.pyx
  spacy/tests/doc/test_doc_api.py
  spacy/tests/doc/test_to_json.py
  spacy/tests/matcher/test_phrase_matcher.py
  spacy/tests/test_gold.py
  spacy/tests/test_json_schemas.py
  spacy/tests/test_misc.py
  spacy/tokens/doc.pyx
  spacy/tokens/printers.py
  spacy/util.py
  website/api/_top-level/_util.jade
  website/api/cli.jade
Labels: enhancement, feat / doc, training, 🌙 nightly

#2985 replace user-facing references to "sbd" with "sentencizer"
  .github/contributors/gavrieltal.md
  spacy/errors.py
  spacy/language.py
  spacy/pipeline.pyx
  website/usage/_linguistic-features/_sentence-segmentation.jade
  website/usage/_processing-pipelines/_extensions.jade
Labels: bug, docs, feat / pipeline
