Repository explosion/spaCy, pull requests merged in 2023-01, with the labels that each got.

#12038 Add spacy-pythainlp
  website/meta/universe.json
Labels: docs, lang / th, universe

#12049 Sync v4 with latest from master
  requirements.txt
  setup.cfg
  spacy/cli/apply.py
  spacy/errors.py
  spacy/pipeline/span_ruler.py
  spacy/pipeline/textcat.py
  spacy/tests/pipeline/test_textcat.py
  spacy/training/loggers.py
  website/docs/api/top-level.md
  website/meta/universe.json
Labels: meta

#12040 Delete unused imports for StringStore
  spacy/lexeme.pxd
  spacy/tokenizer.pxd
Labels: enhancement

#12047 Fix inconsistency in displaCy docs about page option
  spacy/displacy/__init__.py
  spacy/displacy/render.py
  website/docs/api/top-level.md
Labels: docs, feat / visualizers

#12050 fix processing of "auto" in convert
  spacy/cli/_util.py
  spacy/cli/convert.py
  spacy/tests/test_cli.py
  spacy/tests/test_cli_app.py
Labels: bug, feat / cli, 🔜 v3.5

#11820 Improve score_cats for use with multiple textcat components
  spacy/pipeline/textcat_multilabel.py
  spacy/scorer.py
  spacy/tests/pipeline/test_textcat.py
  spacy/tests/test_language.py
Labels: bug, feat / textcat, feat / pipeline, feat / scorer, 🔜 v3.5

#11948 improve ux for displacy when the serve port is in use
  spacy/displacy/__init__.py
  spacy/errors.py
  spacy/tests/test_misc.py
  spacy/util.py
  website/docs/api/top-level.md
Labels: enhancement, feat / visualizers, feat / ux, 🔜 v3.5

#11359 Enable fuzzy text matching in Matcher
  spacy/matcher/levenshtein.pyx
  spacy/matcher/matcher.pxd
  spacy/matcher/matcher.pyi
  spacy/matcher/matcher.pyx
  spacy/pipeline/entityruler.py
  spacy/pipeline/span_ruler.py
  spacy/schemas.py
  spacy/tests/matcher/test_levenshtein.py
  spacy/tests/matcher/test_matcher_api.py
  spacy/tests/pipeline/test_entity_ruler.py
  website/docs/api/entityruler.md
  website/docs/api/matcher.md
  website/docs/api/spanruler.md
  website/docs/usage/rule-based-matching.md
Labels: enhancement, feat / matcher, 🔜 v3.5

#12073 Restore v2 token_acc score implementation
  spacy/scorer.py
  spacy/tests/test_scorer.py
  website/docs/api/scorer.md
Labels: bug, feat / scorer, 🔜 v3.5

#12092 Allow spacy-transformers v1.2.x in transformers extra
  setup.cfg
Labels: meta, feat / transformer

#12089 Clean up displacy port-related error messages, docs
  spacy/errors.py
  website/docs/api/top-level.mdx
Labels: docs, feat / visualizers, 🔜 v3.5

#11902 Add a `spacy benchmark speed` subcommand
  spacy/cli/__init__.py
  spacy/cli/_util.py
  spacy/cli/benchmark_speed.py
  spacy/cli/evaluate.py
  spacy/tests/test_cli_app.py
  website/docs/api/cli.mdx
Labels: feat / cli, perf / speed, 🔜 v3.5

#12098 Handle missing annotations in the edit tree lemmatizer
  spacy/pipeline/edit_tree_lemmatizer.py
  spacy/tests/pipeline/test_edit_tree_lemmatizer.py
Labels: bug, feat / lemmatizer, 🔜 v3.5

#12036 Fix required maximum version of typing-extensions
  requirements.txt
  setup.cfg
Labels: install, third-party

#12095 Fix anchors in StringStore docs
  website/docs/api/stringstore.mdx
Labels: docs, 🔜 v4.0

#12016 Add `TrainablePipe.{distill,get_teacher_student_loss}`
  spacy/errors.py
  spacy/ml/callbacks.py
  spacy/pipeline/edit_tree_lemmatizer.py
  spacy/pipeline/pipe.pyx
  spacy/pipeline/tagger.pyx
  spacy/pipeline/trainable_pipe.pyx
  spacy/pipeline/transition_parser.pyx
  spacy/tests/parser/test_ner.py
  spacy/tests/parser/test_parse.py
  spacy/tests/pipeline/test_edit_tree_lemmatizer.py
  spacy/tests/pipeline/test_morphologizer.py
  spacy/tests/pipeline/test_senter.py
  spacy/tests/pipeline/test_tagger.py
  spacy/tests/pipeline/test_textcat.py
  spacy/tests/training/test_training.py
  spacy/training/__init__.py
  spacy/training/example.pyx
  website/docs/api/dependencyparser.mdx
  website/docs/api/edittreelemmatizer.mdx
  website/docs/api/entityrecognizer.mdx
  website/docs/api/morphologizer.mdx
  website/docs/api/pipe.mdx
  website/docs/api/sentencerecognizer.mdx
  website/docs/api/tagger.mdx
  website/docs/api/top-level.mdx
  website/docs/usage/processing-pipelines.mdx
Labels: enhancement, training, 🔜 v4.0

#12102 Clarify how `--code` arg works
  website/docs/usage/saving-loading.mdx
Labels: docs

#12113 Fix comments and examples for levenshtein_compare
  spacy/matcher/levenshtein.pyx
  website/docs/usage/rule-based-matching.mdx
Labels: docs, feat / matcher

#10940 Merge the parser refactor into `v4`
  setup.py
  spacy/cli/templates/quickstart_training.jinja
  spacy/errors.py
  spacy/ml/_precomputable_affine.py
  spacy/ml/models/parser.py
  spacy/ml/parser_model.pxd
  spacy/ml/parser_model.pyx
  spacy/ml/tb_framework.pxd
  spacy/ml/tb_framework.py
  spacy/ml/tb_framework.pyx
  spacy/pipeline/_parser_internals/_beam_utils.pyx
  spacy/pipeline/_parser_internals/_parser_utils.pxd
  spacy/pipeline/_parser_internals/_parser_utils.pyx
  spacy/pipeline/_parser_internals/_state.pxd
  spacy/pipeline/_parser_internals/arc_eager.pyx
  spacy/pipeline/_parser_internals/batch.pxd
  spacy/pipeline/_parser_internals/batch.pyx
  spacy/pipeline/_parser_internals/ner.pyx
  spacy/pipeline/_parser_internals/stateclass.pyx
  spacy/pipeline/_parser_internals/transition_system.pxd
  spacy/pipeline/_parser_internals/transition_system.pyx
  spacy/pipeline/dep_parser.py
  spacy/pipeline/ner.py
  spacy/pipeline/transition_parser.pxd
  spacy/pipeline/transition_parser.pyx
  spacy/tests/parser/test_ner.py
  spacy/tests/parser/test_parse.py
  spacy/tests/pipeline/test_tok2vec.py
  spacy/tests/serialize/test_serialize_config.py
  spacy/tests/test_misc.py
  spacy/training/example.pyx
  website/docs/api/architectures.mdx
  website/docs/api/cli.mdx
  website/docs/api/legacy.mdx
  website/docs/usage/embeddings-transformers.mdx
Labels: enhancement, gpu, feat / parser, 🔜 v4.0

#12119 Update Dockerfile to work with Next.js
  website/.dockerignore
  website/Dockerfile
  website/README.md
Labels: docs

#12094 Fix batching regression
  pyproject.toml
  requirements.txt
  setup.cfg
  spacy/tests/pipeline/test_tagger.py
  spacy/tests/pipeline/test_textcat.py
  spacy/tests/training/test_training.py
  spacy/training/batchers.py
  spacy/util.py
  website/docs/api/top-level.mdx
Labels: bug, feat / training, 🔜 v4.0

#12120 Move all website gitignore settings to website/.gitignore
  .gitignore
  website/.gitignore
Labels: meta

#12126 Set version to v4.0.0.dev0
  spacy/about.py
Labels: 🔜 v4.0

#12127 update docs for apply
  website/docs/api/cli.mdx
Labels: docs

#12107 Update years in website landing page
  website/pages/index.tsx
Labels: docs

#12121 Revert "Temporarily skip tests that require models/compat"
  .github/azure-steps.yml
  spacy/tests/test_cli.py
Labels: 🔜 v3.5

#12057 3.5 usage page
  website/docs/usage/v3-5.mdx
  website/meta/sidebars.json
  website/src/styles/list.module.sass
  website/src/templates/index.js
Labels: docs, 🔜 v3.5

#12132 Update README for v3.5
  README.md
Labels: docs, 🔜 v3.5

#12137 Fix broken social media image
  website/src/components/seo.js
Labels: docs

#12017 Fix speed problem with `top_k>1` on CPU in edit tree lemmatizer
  spacy/pipeline/edit_tree_lemmatizer.py
  spacy/tests/pipeline/test_edit_tree_lemmatizer.py
Labels: enhancement, feat / lemmatizer, perf / speed

#12051 Add how to load probability tables to existing models to spaCy docs
  website/docs/usage/saving-loading.mdx
Labels: docs

#12129 Fix Azure ignoring website files
  azure-pipelines.yml
Labels: meta

#12158 WEB-30 spaCy pattern in `.png`
  website/src/components/landing.js
  website/src/components/main.js
  website/src/images/pattern_blue.jpg
  website/src/images/pattern_blue.png
  website/src/images/pattern_green.jpg
  website/src/images/pattern_green.png
  website/src/images/pattern_landing.jpg
  website/src/images/pattern_landing.png
  website/src/images/pattern_landing_legacy.jpg
  website/src/images/pattern_landing_legacy.png
  website/src/images/pattern_landing_nightly.jpg
  website/src/images/pattern_landing_nightly.png
  website/src/images/pattern_legacy.jpg
  website/src/images/pattern_legacy.png
  website/src/images/pattern_nightly.jpg
  website/src/images/pattern_nightly.png
  website/src/images/pattern_purple.jpg
  website/src/images/pattern_purple.png
  website/src/styles/landing.module.sass
  website/src/styles/main.module.sass
  website/src/widgets/styleguide.js
Labels: docs

#12160 Add missing label
  website/src/components/copy.js
  website/src/widgets/project.js
Labels: docs

#12161 Fix GitHub badge
  website/src/templates/universe.js
Labels: docs

#12162 WEB-22 Update Explosion logo
  website/src/images/explosion.svg
Labels: docs

#12165 WEB-28 Increase contrast of text and theme color
  website/src/components/juniper.js
  website/src/styles/accordion.module.sass
  website/src/styles/alert.module.sass
  website/src/styles/button.module.sass
  website/src/styles/code.module.sass
  website/src/styles/footer.module.sass
  website/src/styles/infobox.module.sass
  website/src/styles/landing.module.sass
  website/src/styles/layout.sass
  website/src/styles/link.module.sass
  website/src/styles/navigation.module.sass
  website/src/styles/newsletter.module.sass
  website/src/styles/quickstart.module.sass
  website/src/styles/readnext.module.sass
  website/src/styles/search.sass
  website/src/styles/sidebar.module.sass
  website/src/styles/table.module.sass
  website/src/styles/tag.module.sass
  website/src/styles/typography.module.sass
Labels: docs

#12166 WEB-27 Add `alt` tags to images
  website/docs/usage/101/_vectors-similarity.mdx
  website/docs/usage/layers-architectures.mdx
  website/docs/usage/projects.mdx
  website/docs/usage/spacy-101.mdx
  website/docs/usage/visualizers.mdx
  website/pages/index.tsx
  website/src/components/card.js
  website/src/components/title.js
  website/src/templates/universe.js
Labels: docs

#12159 Remove unnecessary links on website
  website/src/components/embed.js
Labels: docs

#12151 Fix wrong HTML element attribute in website front page
  website/src/components/embed.js
Labels: docs

#12169 Fix navigation alert
  website/src/templates/index.js
Labels: docs

#12125 Refactor lexeme mem passing
  spacy/lexeme.pyx
  spacy/tokenizer.pxd
  spacy/tokenizer.pyx
  spacy/tokens/doc.pyx
  spacy/tokens/retokenizer.pyx
  spacy/vocab.pxd
  spacy/vocab.pyx
  website/docs/api/cython-classes.mdx
Labels: 🔜 v4.0

#12171 Fix broken syntax for type annotations
  website/docs/api/cli.mdx
Labels: docs

#12172 Fix regression with links in prompts
  website/src/components/code.js
Labels: docs

#12176 Fix broken URL in docs
  website/meta/universe.json
Labels: universe

#12178 WEB-28 Increase contrast of grey text
  website/src/components/juniper.js
  website/src/styles/layout.sass
Labels: docs

#12179 Add `aria-label` to quickstart widget
  website/src/components/quickstart.js
Labels: docs

#12182 CI: Add black formatting check to validation
  azure-pipelines.yml
Labels: meta

#12153 Update binder version to v3.5
  website/meta/site.json
Labels: docs

#12183 Fix text color in docs
  website/src/components/landing.js
  website/src/styles/code.module.sass
  website/src/styles/landing.module.sass
Labels: docs

#12184 Fix frontpage image
  website/pages/index.tsx
Labels: docs

#12185 CI: Extend website excludes
  azure-pipelines.yml
Labels: meta

#12175 Load components dynamically (decrease initial file size for docs)
  website/pages/index.tsx
  website/src/components/code.js
  website/src/components/codeBlock.js
  website/src/components/codeDynamic.js
  website/src/components/embed.js
  website/src/components/github.js
  website/src/components/htmlToReact.js
  website/src/components/inlineCode.js
  website/src/components/landing.js
  website/src/components/markdownToReact.js
  website/src/components/markdownToReactDynamic.js
  website/src/components/title.js
  website/src/components/typeAnnotation.js
  website/src/components/util.js
  website/src/remark.js
  website/src/templates/index.js
  website/src/templates/models.js
  website/src/templates/universe.js
  website/src/widgets/changelog.js
  website/src/widgets/languages.js
  website/src/widgets/project.js
  website/src/widgets/quickstart-training.js
Labels: docs

#12186 Fix even more color problems
  website/src/styles/aside.module.sass
  website/src/styles/quickstart.module.sass
Labels: docs

#12122 Add `spacy.PlainTextCorpusReader.v1`
  spacy/tests/training/test_corpus.py
  spacy/training/__init__.py
  spacy/training/corpus.py
  website/docs/api/corpus.mdx
Labels: enhancement, feat / training

#11419 `trainable_lemmatizer` in `debug data`
  spacy/cli/debug_data.py
  spacy/tests/test_cli.py
  spacy/tests/test_cli_app.py
Labels: enhancement, feat / cli

#12145 Add alignment_mode argument to Span.char_span()
  spacy/tests/doc/test_span.py
  spacy/tokens/span.pyi
  spacy/tokens/span.pyx
  website/docs/api/span.mdx
Labels: enhancement, feat / doc

#12196 Add span_id to Span.char_span, update Doc/Span.char_span docs
  spacy/tests/doc/test_span.py
  spacy/tokens/doc.pyi
  spacy/tokens/doc.pyx
  spacy/tokens/span.pyi
  spacy/tokens/span.pyx
  website/docs/api/doc.mdx
  website/docs/api/span.mdx
Labels: bug, docs, feat / doc

#12189 Add KB breaking change to usage docs
  website/docs/usage/v3-5.mdx
Labels: docs, 🔜 v3.5

#12187 Drop python 3.6/3.7, remove unneeded compat
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  README.md
  azure-pipelines.yml
  requirements.txt
  setup.cfg
  spacy/cli/_util.py
  spacy/cli/debug_data.py
  spacy/compat.py
  spacy/errors.py
  spacy/language.py
  spacy/matcher/matcher.pyi
  spacy/matcher/phrasematcher.pyi
  spacy/ml/models/parser.py
  spacy/pipeline/spancat.py
  spacy/schemas.py
  spacy/ty.py
  spacy/util.py
  website/docs/usage/index.mdx
Labels: 🔜 v4.0

#12194 Add extra flag to assets docs
  website/docs/api/cli.mdx
Labels: docs, feat / cli, projects

#12116 Add `Language.distill`
  spacy/language.py
  spacy/pipeline/trainable_pipe.pyx
  spacy/pipeline/transition_parser.pyx
  spacy/tests/test_language.py
  spacy/ty.py
  website/docs/api/dependencyparser.mdx
  website/docs/api/edittreelemmatizer.mdx
  website/docs/api/entityrecognizer.mdx
  website/docs/api/language.mdx
  website/docs/api/morphologizer.mdx
  website/docs/api/pipe.mdx
  website/docs/api/sentencerecognizer.mdx
  website/docs/api/tagger.mdx
Labels: enhancement, feat / pipeline, 🔜 v4.0

#12188 Don't re-download installed models
  .github/azure-steps.yml
  spacy/cli/download.py
Labels: enhancement, feat / cli

#12201 Add the configuration schema for distillation
  spacy/cli/init_config.py
  spacy/default_config_distillation.cfg
  spacy/language.py
  spacy/schemas.py
  spacy/tests/serialize/test_serialize_config.py
Labels: enhancement, feat / config

#12209 Language.distill: copy both reference and predicted
  spacy/language.py
Labels: bug

#12210 Remove flaky assertions in `test_cli_find_threshold()`
  spacy/tests/test_cli.py
Labels: bug, tests, feat / cli

#12149 Rename language codes (Icelandic, multi-language)
  spacy/cli/_util.py
  spacy/cli/convert.py
  spacy/cli/init_config.py
  spacy/cli/init_pipeline.py
  spacy/errors.py
  spacy/lang/isl/__init__.py
  spacy/lang/isl/stop_words.py
  spacy/lang/mul/__init__.py
  spacy/lang/mul/examples.py
  spacy/scorer.py
  spacy/tests/README.md
  spacy/tests/conftest.py
  spacy/tests/doc/test_doc_api.py
  spacy/tests/lang/isl/__init__.py
  spacy/tests/lang/isl/test_text.py
  spacy/tests/lang/isl/test_tokenizer.py
  spacy/tests/lang/mul/__init__.py
  spacy/tests/lang/mul/test_text.py
  spacy/tests/lang/mul/test_tokenizer.py
  spacy/tests/lang/test_initialize.py
  spacy/tests/pipeline/test_span_ruler.py
  spacy/tests/test_language.py
  spacy/tests/tokenizer/test_explain.py
  spacy/training/converters/conll_ner_to_docs.py
  spacy/training/converters/json_to_docs.py
  spacy/util.py
  website/docs/api/scorer.mdx
  website/docs/usage/models.mdx
  website/meta/languages.json
  website/src/widgets/quickstart-models.js
Labels: enhancement, 🔜 v4.0
