Repository explosion/spaCy, pull requests merged in 2024-03, with the labels that each got.

#13391 remove smart_open requirement
  requirements.txt
  setup.cfg
Labels: enhancement

#13366 extend abbreviations list in Faroese tokenizer exceptions
  spacy/lang/fo/tokenizer_exceptions.py
Labels: feat / tokenizer, lang / fo

#13395 Renamed main branch back to v4 for now
  .github/workflows/gputests.yml
  .github/workflows/slowtests.yml
Labels: meta

#13379 Update code.module.sass to make code title sticky
  website/src/styles/code.module.sass
Labels: docs
